all:
	@$(CC) -c main.c -I../include -o ../$(OBJS_DIR)/main.o
	@$(CC) -c communication.c -I../include -o ../$(OBJS_DIR)/communication.o
	@$(CC) -c register.c -I../include -o ../$(OBJS_DIR)/register.o
	@$(CC) -c login.c -I../include -o ../$(OBJS_DIR)/login.o
	@$(CC) -c search.c -I../include -o ../$(OBJS_DIR)/search.o
	@$(CC) -c list_his.c -I../include -o ../$(OBJS_DIR)/list_his.o
	@$(CC) -c debug.c -I../include -o ../$(OBJS_DIR)/debug.o

